name: Issue Report
description: 기본 이슈 양식 <= 이것으로 사용합니다.
title: '[]: '
# labels: ["bug", "triage"]
projects: ['freshman-front/1']
assignees:
    - octocat
body:
    - type: markdown
      attributes:
          value: |
              ✅ 구현할 내용을 입력해주세요
    - type: checkboxes
      id: terms
      attributes:
          label: 체크 항목 리스트
          description:
          options:
              - label: ''
                required: true
